### ISSUE TITLE
Why type torch.FloatTensor but got torch.cuda.FloatTensor?

### ISSUE THREAD

**Issue by zhuwanling** [sefibk/KernelGAN#1]
Thank you for sharing.
I get a error: RuntimeError: Function AddBackward0 returned an invalid gradient at index 1 - expected type torch.FloatTensor but got torch.cuda.FloatTensor
In   # Calculate gradientstotal_loss_g.backward()
We have made any changes.

**Comment by sefibk** [comment]
Sorry but I am not sure. 
Did you follow the .yml file precisely?
