### ISSUE TITLE
Question about ZSSR config

### ISSUE THREAD

**Issue by jfun9494** [sefibk/KernelGAN#18]
I have a couple of questions regarding ZSSR configs:
1) I noticed that in the run_zssr function, real_img and noise_scale are completely ignored, and only scale_factor and kernel are specified in these lines: https://github.com/sefibk/KernelGAN/blob/cb8829330183e8d1c4b7e1fd05427d217cb16f59/util.py#L225-L228
Can you please clarify if my observation is right?

2) In [this issue](https://github.com/assafshocher/ZSSR/issues/8) the author mentions that ZSSR may run in to division problems when using python3. Is the ZSSR code in this repo susceptible to this kind of problem?

**Comment by jfun9494** [comment]
Regarding the first question. I changed up the function so that ZSSR takes real_img and noise_scale arguments. I am getting much better results on my test image and the artifacts are gone.

**Comment by sefibk** [comment]
1. You are on to a serious bug. Thank you. 
I would appreciate if you open a pr and I will approve it
2. Yes, I solved that issue in this ZSSR code

**Comment by jfun9494** [comment]
I created [PR](https://github.com/sefibk/KernelGAN/pull/19)

**Comment by sefibk** [comment]
MERGED - thanks so much for the help
