### ISSUE TITLE
Kernel estimation size problem

### ISSUE THREAD

**Issue by circlehy** [sefibk/KernelGAN#2]
Training with image 'DIV2KRK/lr_x2/im_78.png', the ground truth kernel should be 'gt_k_x2/kernel_78.mat'  right? The generated result kernel size seems different from the ground truth kernel? Is this the final result?

**Comment by circlehy** [comment]
Besides, the code seems sum five different loss , not the four different loss mentioned in the paper? and the corresponding  parameter is different from the paper
paper:
![Screenshot from 2019-10-17 17-34-25](https://user-images.githubusercontent.com/9382038/67013659-8381dd00-f104-11e9-8a2f-f7cde0227956.png)
code:
![Screenshot from 2019-10-17 17-36-45](https://user-images.githubusercontent.com/9382038/67013807-c2b02e00-f104-11e9-8a9a-2a391d7a2684.png)
code parameters:
![Screenshot from 2019-10-17 17-38-09](https://user-images.githubusercontent.com/9382038/67013928-fab77100-f104-11e9-89c7-a14b17c2cc73.png)
Please correct me if I configed the code wrong.

**Comment by sefibk** [comment]
Q1: We assume the GT kernel is unknown and also its size. KernelGAN estimates a 13x13, 25x25 kernel for X2, X4 respectively. These are sizes we found give a wide enough and "natural" support (a larger one blurs too much and a smaller is not expressive enough). If you want to compare two different size kernels - you may pad the smaller one with zeros without effecting its blur function.

Q2: As written in the paper, all the regularizations are inserted after the bicubic constraint is satisfied and discarded. The final co-efficients are as written in the paper (and you quoted). The parameters you snapped are at the beginning of the training before the bicubic "satisfaction".
