### ISSUE TITLE
Output Kernel Size

### ISSUE THREAD

**Issue by tingkuei** [sefibk/KernelGAN#20]
Dear Author:

Thank you for your excellent work. 
Recently I am running the kernel gan, and trying to downscale my images by the learned kernel. I found that the resultant kernel sizes is 17x17 ( for X2) and 33x33 (for X4). When I go back to your paper, the size of kernels are 13 x 13 and 25 x 25 respectively.
Is there any other configuration that I missed for the training?

Thank you!

Thank you!

**Comment by sefibk** [comment]
I don't recall such problem.
When you say - the resultant kernel - do you refer to the .mat file that is saved?

**Comment by tingkuei** [comment]
Yes, I check the shape of the resultant kernel in .mat file.

**Comment by sefibk** [comment]
That is somewhat surprising if you didn't change any configs.
I currently don't have time to check this issue but just to clarify:
A 17x17 kernel is IDENTICAL to a 13x13 kernel zero-padded with 2 pixels.
Therefore, if the boundaries values are negligible (which they should be) - simply resize the kernel to the desired size and it will keep the correct solution. 
Practically (and physically) - the size of the kernel does not matter AT ALL as far as the extra values are zero or close to it - hope that is understood.
Sorry if there is a bug, I will get around to it sometime soon

**Comment by tingkuei** [comment]
I think the down-scaled image look good. I just want to check the details.

Thank you. 

TK
