### ISSUE TITLE
Constraint co-efficients in code different from paper

### ISSUE THREAD

**Issue by jixiaozhong** [sefibk/KernelGAN#22]
Thanks for your great work!
I am confused about the constraint co-efficients:
In your code: https://github.com/sefibk/KernelGAN/blob/master/kernelGAN.py#L9-L14
In your paper:
![image](https://user-images.githubusercontent.com/22931606/83110005-f7518280-a0f4-11ea-88e6-ce147f23c8b8.png)
Could you please tell me which is the right version?

**Comment by sefibk** [comment]
Some coefficients change during training.
The center + sparse constraints are inserted after the Bicubic constraint is satisfied.
