### ISSUE TITLE
real LR

### ISSUE THREAD

**Issue by zhuangzhong** [sefibk/KernelGAN#23]
hello,friend. I have a LR and filter.How get real LR?

**Comment by sefibk** [comment]
Question is not clear

**Comment by zhuangzhong** [comment]
I'm sorry. I'm wrong. My problem is that I downloaded the data  of DIV2KRK, which contains the kernel. I want to know how to generate real LR according to div2k HR and kernel

**Comment by sefibk** [comment]
Both the LR and HR are provided in the DIV2K-RK.
If you want to know how to reproduce the LR you can simply use the [imresize](https://github.com/sefibk/KernelGAN/blob/master/imresize.py) function with the HR and the kernel

**Comment by zhuangzhong** [comment]
thanks
