### ISSUE TITLE
Adjust the blurring level of output LR

### ISSUE THREAD

**Issue by tingkuei** [sefibk/KernelGAN#25]
Dear Author,

Thank you for your excellent work. Recently I am trying to generate some LR images from my HR images. The output LR from the estimated kernel is too blurred for my case. Is it possible to generate a LR that is less blurred. My guess is to adjust the filter size of generator, it is correct?

Best,

TK

**Comment by sefibk** [comment]
No
It depends on the reason you are trying to create the HR-LR pairs. If you just want a dataset for some reason - try using "thin" kernels. 
The kernel estimated by the generator is the SR kernel it self. 
Try specifying what is your goal. I am not sure KernelGAN is of interest to you

**Comment by tingkuei** [comment]
Hi Author,

Yes, I am trying to do the SR work. Thus, my goal is to create LR-HR Pairs. In my dateset, the LR is too blurred so that the super-resolved network seems behaving too aggressive.  I think the main reason is that the blurred kernel size is 33x33 ( for x4), which will produce a more blurred LR images.
I want to try kernels of different size, (maybe 20 x 20 for x4). For thin kernels, do you mean to reduce the layer of generator or reduce the size of filters?


Best,

TK

**Comment by sefibk** [comment]
Again, the KernelGAN will estimate the specific SR kernel. Changing architecture or other things might hurt the results and give undesired artifacts. 
If you simply want to creat sharper LR images, you can use the x2 kernel to downscale by 4 but it is physically wrong. 
Hope this helps
