### ISSUE TITLE
Kernel_shift function clarification

### ISSUE THREAD

**Issue by jfun9494** [sefibk/KernelGAN#27]
I noticed that in the [post_process function here](https://github.com/sefibk/KernelGAN/blob/7218a37f0933519513aac97f40b8a72d3676eec9/util.py#L129) a kernel_shift is applied to the kernel with sf=2.

Because sf=2, the center of mass of the kernel becomes shifted: https://github.com/sefibk/KernelGAN/blob/7218a37f0933519513aac97f40b8a72d3676eec9/imresize.py#L186

Could you clarify, why we need to satisfy the 2nd condition in the kernel_shift function (about top left pixel)? Why do we make the center of mass not placed in the true center of mass and why should it depend on the scale factor?

**Comment by sefibk** [comment]
Excellent question that we spent a while on.
In this work we suggest to choose odd kernel sizes for this reason but we support even sized kernels.
In the downscaled image, pixel 1,1 (top left) should be the results of a convolution with a kernel that is centralized around the sfxsf top left pixels (hope this is clear...). 
The way a convolution is implemented in Scipy, it places the kernel's center (depending on the kernel size) up and left from what we want. **If I recall correctly**, for odd size it places the center on the top left pixel=1,1, and for even size it goes even further up and left.
Therefore, to get a "physically" correct downscaling (without subpixel shifts) we must shift it down and right.
Hope this was clear.

**Comment by jfun9494** [comment]
Thank you for your response. After some experiments I found that it is not actually the correlate function in Scipy that shifts the image, but the downsampling after it (which is nearest neighbor downsampling). We can get the similar image by correlating with centralized kernel (without kernel_shift) and then downsampling with average pooling.

**Comment by sefibk** [comment]
I don't remember the details you are noting and definitely there might be 2 ways to do it correctly. If you find something wrong in my implementation please let me know.
