### ISSUE TITLE
question about  function resize_tensor_w_kernel

### ISSUE THREAD

**Issue by guangpintao** [sefibk/KernelGAN#28]
DownScaleLoss uses bicubic kernel to conv the img tensor,g_input'shape is [1,3,64,64]
![image](https://user-images.githubusercontent.com/32570671/84848238-603d7200-b085-11ea-943e-b1d76b1b60b1.png),in this expanding and conv2d way,i think the bicubic downsampling will get black-white img,and it is used in bicubic loss later,i'm confused about this.

**Comment by sefibk** [comment]
It shouldn’t. You can run it to see. 
It expands the kernel to 3 IDENTICAL channels in order to downscale all channels with a single kernel

**Comment by guangpintao** [comment]
K's second dimension provides 3 IDENTICAL channels,but expanding as the first dimension( out_channels: 3 ) will cause to use the same kernel to get out_channels,I think it should be Group Convolution instead.

I use it to get bicubic downscaled img using function in code:
![im_0](https://user-images.githubusercontent.com/32570671/84897662-90623080-b0d8-11ea-88b8-9f8497bde52c.png)
![result](https://user-images.githubusercontent.com/32570671/84897666-935d2100-b0d8-11ea-88ef-b6cc73a1ef2e.png)
![image](https://user-images.githubusercontent.com/32570671/84898026-27c78380-b0d9-11ea-818a-68a3aeece959.png)

I use  Group Convolution and get:
![result](https://user-images.githubusercontent.com/32570671/84898148-5f363000-b0d9-11ea-82e1-0bf4a8c704a3.png)
![image](https://user-images.githubusercontent.com/32570671/84898201-7412c380-b0d9-11ea-9ad3-fe5c28743baf.png)
