### ISSUE TITLE
windows device - tensorflow version issues

### ISSUE THREAD

**Issue by benGISI** [sefibk/KernelGAN#30]
I am trying to run the program on a windows laptop but i keep running into the following error when running the ZSSR after the Kernal is done:
Loaded runtime CuDNN library: 7.0.5 but source was compiled with: 7.1.4. CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library. If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.

I was wondering on what system you are running your code and if you came across this issue.
I checked my system and can't find a 7.0.5 version of CuDNN.

**Comment by sefibk** [comment]
Linux. 
Sorry but don't know how to solve this issue

**Comment by benGISI** [comment]
Thanks, 

I got the code to work but on large images I get an error that I don't have enough memory on the GPU.
Can you tell what GPU you used? maybe my GPU is not strong enough

**Comment by sefibk** [comment]
The smallest I tried was k80 and it ran with no problem

**Comment by benGISI** [comment]
Thanks, I'll give it a try
