### ISSUE TITLE
[feature] Add Dockerfile to allow easy reproduction.

### ISSUE THREAD

**Issue by MagicFrogSJTU** [sefibk/KernelGAN#39]
As title.
A Dockerfile can solve the problem, easy and quick!

**Comment by sefibk** [comment]
IDK much about dockers.
requirement.txt should be enough to reproduce

**Comment by MagicFrogSJTU** [comment]
In practice, I found tensorflow version and the cuda version a little annoying.
I can write the Dockerfile and make a PR. It may help!
