### ISSUE TITLE
For real images, the reconstruction results in a smooth transition

### ISSUE THREAD

**Issue by zerodohero** [sefibk/KernelGAN#42]
As shown in the figure above, the reconstructed image on the left is overly smoothAre all the hyperparameters in the code tuned?Does the adjustment of hyperparameters have much effect on the results?
![20200730173915](https://user-images.githubusercontent.com/38395598/88908824-f4a61180-d28c-11ea-8e91-c734133ea949.png)

**Comment by sefibk** [comment]
The specified parameters fit the "average" image after reviewing several.
Images with more or with less noise require adjusting the network.
You can try to tune the --noise_scale added to ZSSR to get a better image.
FYI - KernelGAN works best for natural images. Every so often, you might get images where performance will deteriorate...

**Comment by zerodohero** [comment]
> The specified parameters fit the "average" image after reviewing several.
> Images with more or with less noise require adjusting the network.
> You can try to tune the --noise_scale added to ZSSR to get a better image.
> FYI - KernelGAN works best for natural images. Every so often, you might get images where performance will deteriorate...

Thank you very much

I will try your advice
