### ISSUE TITLE
Question about kernel estimation 

### ISSUE THREAD

**Issue by rptxk01** [sefibk/KernelGAN#56]
Hi, thank you for the great work. I have a question regarding the paper.

KernelGAN estimates down-scale kernel from LR and 
considers that kernel to be the kernel of unknown clean HR.

I am wondering if there are domain-related problems in the process.

For example, if LR is highly degraded by blur or compression,
the estimated kernel will map "degraded LR" → "degraded down-scaled LR".
However, the ideal kernel should be "clean HR" → "degraded LR" in this case.

I think the domain mismatch may deteriorate the restored SR quality.

Could you enlighten me on this concern? Thanks a lot.

**Comment by sefibk** [comment]
The "non-formal" answer is that the SR task is different than the deblurring and denoising task - it generally deals with clean images that were downscaled and "lightly" downgraded. It doesn't deal with severe degradations. 
Regarding deblurring and denoising, we had an idea to apply KernelGAN for that however it is not straight forward and didn't work for us with our first try.

**Comment by rptxk01** [comment]
Thanks for the detailed replies.
The comments inspired me a lot.
