### ISSUE TITLE
A question about "--real"

### ISSUE THREAD

**Issue by Vonuo** [sefibk/KernelGAN#58]
Hi, thank you for your Code sharing. 
I'm confused about  "--real : Real-image configuration (effects only the ZSSR)" in usage, is it mean ZSSR in this mode is trained by real data?

**Comment by sefibk** [comment]
ZSSR trains only on the single test image. The real flags inform ZSSR that this test image is real (i.e. has noise) and therefore adds noise when downscaling the image.
To conclude it effects only ZSSR

**Comment by Vonuo** [comment]
> ZSSR trains only on the single test image. The real flags inform ZSSR that this test image is real (i.e. has noise) and therefore adds noise when downscaling the image.
> To conclude it effects only ZSSR

**Comment by Vonuo** [comment]
> ZSSR trains only on the single test image. The real flags inform ZSSR that this test image is real (i.e. has noise) and therefore adds noise when downscaling the image.
> To conclude it effects only ZSSR


So, "--real" correspond to "Ground-truth kernel + ZSSR" that listed in table 1(yellow marked)?
![img](https://user-images.githubusercontent.com/22700431/108709969-5e01b080-754e-11eb-8162-621e513833ac.PNG)

**Comment by sefibk** [comment]
No
--real is a flag that modifies ZSSR for real images. 
In synthetic images (as opposed to real) images are "clean" and there is no noise.
What ZSSR does when there is noise (i.e. the flag --real is true) is it adds noise to the downscaled version of the input image.

**Comment by Vonuo** [comment]
> No
> --real is a flag that modifies ZSSR for real images.
> In synthetic images (as opposed to real) images are "clean" and there is no noise.
> What ZSSR does when there is noise (i.e. the flag --real is true) is it adds noise to the downscaled version of the input image.

Ok, I understand.
Thank you!
