### ISSUE TITLE
No file  .mat

### ISSUE THREAD

**Issue by cgysjy** [sefibk/KernelGAN#80]
Please !How can I solve this problem？Thank you!
![image](https://user-images.githubusercontent.com/125937429/232743778-61d582c2-e307-48a3-99cb-be787fc722d3.png)

**Comment by sefibk** [comment]
Not sure but 2 thoughts:
1. did you download the dataset?
2. Seems like you are using Windows (which I am not familiar with). So I am not sure the code is fit for that and specifically not sure why you have "\\" instead of "\". Try fixing that
